import os
from configparser import ConfigParser


class Issue_Config:

    # Reading Configs
    config = ConfigParser()
    config_path = os.path.join("./config", "issue_list.ini")
    config.read(config_path)

    "Cookies" in config
    ISSUE_COOKIES_SESSION_NAME = config["Cookies"]["ISSUE_COOKIES_SESSION_NAME"]
    ISSUE_COOKIES_SESSION_VALUE = config["Cookies"]["ISSUE_COOKIES_SESSION_VALUE"]
    ISSUE_COOKIES_DOMAIN = config["Cookies"]["ISSUE_COOKIES_DOMAIN"]
    ISSUE_COOKIES_PATH = config["Cookies"]["ISSUE_COOKIES_PATH"]
    ISSUE_COOKIES_EXPIRES = config["Cookies"]["ISSUE_COOKIES_EXPIRES"]
    ISSUE_COOKIES_SECURE = config["Cookies"]["ISSUE_COOKIES_SECURE"]

    SUGGESTION_COOKIES_SESSION_NAME = config["Cookies"]["SUGGESTION_COOKIES_SESSION_NAME"]
    SUGGESTION_COOKIES_SESSION_VALUE = config["Cookies"]["SUGGESTION_COOKIES_SESSION_VALUE"]
    SUGGESTION_COOKIES_DOMAIN = config["Cookies"]["SUGGESTION_COOKIES_DOMAIN"]
    SUGGESTION_COOKIES_PATH = config["Cookies"]["SUGGESTION_COOKIES_PATH"]
    SUGGESTION_COOKIES_EXPIRES = config["Cookies"]["SUGGESTION_COOKIES_EXPIRES"]
    SUGGESTION_COOKIES_SECURE = config["Cookies"]["SUGGESTION_COOKIES_SECURE"]

    "Server Location" in config
    ISSUE_LOCATION_CITY = config["Server Location"]["ISSUE_LOCATION_CITY"]
    ISSUE_LOCATION_COUNTRY = config["Server Location"]["ISSUE_LOCATION_COUNTRY"]
    ISSUE_LOCATION_TIMEZONE = config["Server Location"]["ISSUE_LOCATION_TIMEZONE"]
    ISSUE_LOCATION_LANGUAGES = config["Server Location"]["ISSUE_LOCATION_LANGUAGES"]
    ISSUE_LOCATION_CURRENCY = config["Server Location"]["ISSUE_LOCATION_CURRENCY"]

    SUGGESTION_LOCATION_CITY = config["Server Location"]["SUGGESTION_LOCATION_CITY"]
    SUGGESTION_LOCATION_COUNTRY = config["Server Location"]["SUGGESTION_LOCATION_COUNTRY"]
    SUGGESTION_LOCATION_TIMEZONE = config["Server Location"]["SUGGESTION_LOCATION_TIMEZONE"]
    SUGGESTION_LOCATION_LANGUAGES = config["Server Location"]["SUGGESTION_LOCATION_LANGUAGES"]
    SUGGESTION_LOCATION_CURRENCY = config["Server Location"]["SUGGESTION_LOCATION_CURRENCY"]

    "Server info" in config
    ISSUE_SERVER_INFO_ORGANIZATION = config["Server info"]["ISSUE_SERVER_INFO_ORGANIZATION"]
    ISSUE_SERVER_INFO_ASN = config["Server info"]["ISSUE_SERVER_INFO_ORGANIZATION"]
    ISSUE_SERVER_INFO_IP = config["Server info"]["ISSUE_SERVER_INFO_ORGANIZATION"]
    ISSUE_SERVER_INFO_LOCATION = config["Server info"]["ISSUE_SERVER_INFO_ORGANIZATION"]

    SUGGESTION_SERVER_INFO_ORGANIZATION = config["Server info"]["SUGGESTION_SERVER_INFO_ORGANIZATION"]
    SUGGESTION_SERVER_INFO_ASN = config["Server info"]["SUGGESTION_SERVER_INFO_ASN"]
    SUGGESTION_SERVER_INFO_IP = config["Server info"]["SUGGESTION_SERVER_INFO_IP"]
    SUGGESTION_SERVER_INFO_LOCATION = config["Server info"]["SUGGESTION_SERVER_INFO_LOCATION"]

    "SSL Certificate" in config
    ISSUE_SSL_SUBJECT = config["SSL Certificate"]["ISSUE_SSL_SUBJECT"]
    ISSUE_SSL_ISSUER = config["SSL Certificate"]["ISSUE_SSL_ISSUER"]
    ISSUE_SSL_EXPIRES = config["SSL Certificate"]["ISSUE_SSL_EXPIRES"]
    ISSUE_SSL_RENEWED = config["SSL Certificate"]["ISSUE_SSL_RENEWED"]
    ISSUE_SSL_SERIAL_NUM = config["SSL Certificate"]["ISSUE_SSL_SERIAL_NUM"]
    ISSUE_SSL_FINGERPRINT = config["SSL Certificate"]["ISSUE_SSL_FINGERPRINT"]
    ISSUE_SSL_TLS_WEB_SERVER_AUTH = config["SSL Certificate"]["ISSUE_SSL_TLS_WEB_SERVER_AUTH"]
    ISSUE_SSL_TLS_WEB_CLIENT_AUTH = config["SSL Certificate"]["ISSUE_SSL_TLS_WEB_CLIENT_AUTH"]

    SUGGESTION_SSL_SUBJECT = config["SSL Certificate"]["SUGGESTION_SSL_SUBJECT"]
    SUGGESTION_SSL_ISSUER = config["SSL Certificate"]["SUGGESTION_SSL_ISSUER"]
    SUGGESTION_SSL_EXPIRES = config["SSL Certificate"]["SUGGESTION_SSL_EXPIRES"]
    SUGGESTION_SSL_RENEWED = config["SSL Certificate"]["SUGGESTION_SSL_RENEWED"]
    SUGGESTION_SSL_SERIAL_NUM = config["SSL Certificate"]["SUGGESTION_SSL_SERIAL_NUM"]
    SUGGESTION_SSL_FINGERPRINT = config["SSL Certificate"]["SUGGESTION_SSL_FINGERPRINT"]
    SUGGESTION_SSL_TLS_WEB_SERVER_AUTH = config["SSL Certificate"]["SUGGESTION_SSL_TLS_WEB_SERVER_AUTH"]
    SUGGESTION_SSL_TLS_WEB_CLIENT_AUTH = config["SSL Certificate"]["SUGGESTION_SSL_TLS_WEB_CLIENT_AUTH"]

    "Archive History" in config
    ISSUE_ARCHIVE_HISTORY_FIRST_SCAN = config["Archive History"]["ISSUE_ARCHIVE_HISTORY_FIRST_SCAN"]
    ISSUE_ARCHIVE_HISTORY_LAST_SCAN = config["Archive History"]["ISSUE_ARCHIVE_HISTORY_LAST_SCAN"]
    ISSUE_ARCHIVE_HISTORY_TOTAL_SCANS = config["Archive History"]["ISSUE_ARCHIVE_HISTORY_TOTAL_SCANS"]
    ISSUE_ARCHIVE_HISTORY_CHANGE_COUNTS = config["Archive History"]["ISSUE_ARCHIVE_HISTORY_CHANGE_COUNTS"]
    ISSUE_ARCHIVE_HISTORY_AVG_SIZE = config["Archive History"]["ISSUE_ARCHIVE_HISTORY_AVG_SIZE"]
    ISSUE_ARCHIVE_HISTORY_AVG_DAYS = config["Archive History"]["ISSUE_ARCHIVE_HISTORY_AVG_DAYS"]

    SUGGESTION_ARCHIVE_HISTORY_FIRST_SCAN = config["Archive History"]["SUGGESTION_ARCHIVE_HISTORY_FIRST_SCAN"]
    SUGGESTION_ARCHIVE_HISTORY_LAST_SCAN = config["Archive History"]["SUGGESTION_ARCHIVE_HISTORY_LAST_SCAN"]
    SUGGESTION_ARCHIVE_HISTORY_TOTAL_SCANS = config["Archive History"]["SUGGESTION_ARCHIVE_HISTORY_TOTAL_SCANS"]
    SUGGESTION_ARCHIVE_HISTORY_CHANGE_COUNTS = config["Archive History"]["SUGGESTION_ARCHIVE_HISTORY_CHANGE_COUNTS"]
    SUGGESTION_ARCHIVE_HISTORY_AVG_SIZE = config["Archive History"]["SUGGESTION_ARCHIVE_HISTORY_AVG_SIZE"]
    SUGGESTION_ARCHIVE_HISTORY_AVG_DAYS = config["Archive History"]["SUGGESTION_ARCHIVE_HISTORY_AVG_DAYS"]

    "Associated Hosts" in config
    ISSUE_ASSO_HOSTS = config["Associated Hosts"]["ISSUE_ASSO_HOSTS"]
    SUGGESTION__ASSO_HOSTS = config["Associated Hosts"]["SUGGESTION__ASSO_HOSTS"]

    "Carbon Footprint" in config
    ISSUE_CO2_INITIAL_SIZE = config["Carbon Footprint"]["ISSUE_CO2_INITIAL_SIZE"]
    ISSUE_CO2_INITIAL_LOAD = config["Carbon Footprint"]["ISSUE_CO2_INITIAL_LOAD"]
    ISSUE_CO2_ENERGY_USE = config["Carbon Footprint"]["ISSUE_CO2_ENERGY_USE"]
    ISSUE_CO2_EMITTED = config["Carbon Footprint"]["ISSUE_CO2_EMITTED"]

    SUGGESTION_CO2_INITIAL_SIZE = config["Carbon Footprint"]["SUGGESTION_CO2_INITIAL_SIZE"]
    SUGGESTION_CO2_INITIAL_LOAD = config["Carbon Footprint"]["SUGGESTION_CO2_INITIAL_LOAD"]
    SUGGESTION_CO2_ENERGY_USE = config["Carbon Footprint"]["SUGGESTION_CO2_ENERGY_USE"]
    SUGGESTION_CO2_EMITTED = config["Carbon Footprint"]["SUGGESTION_CO2_EMITTED"]

    "Crawl Rules" in config
    ISSUE_CRAWL_RULES = config["Crawl Rules"]["ISSUE_CRAWL_RULES"]
    SUGGESTION__CRAWL_RULES = config["Crawl Rules"]["SUGGESTION__CRAWL_RULES"]

    "DNS Security" in config
    ISSUE_DNS_SECURITY_DNS_TYPE = config["DNS Security"]["ISSUE_DNS_SECURITY_DNS_TYPE"]
    ISSUE_DNS_SECURITY_RD = config["DNS Security"]["ISSUE_DNS_SECURITY_RD"]
    ISSUE_DNS_SECURITY_RA = config["DNS Security"]["ISSUE_DNS_SECURITY_RA"]
    ISSUE_DNS_SECURITY_TC = config["DNS Security"]["ISSUE_DNS_SECURITY_TC"]
    ISSUE_DNS_SECURITY_AD = config["DNS Security"]["ISSUE_DNS_SECURITY_AD"]
    ISSUE_DNS_SECURITY_CD = config["DNS Security"]["ISSUE_DNS_SECURITY_CD"]

    SUGGESTION__DNS_SECURITY_DNS_TYPE = config["DNS Security"]["SUGGESTION__DNS_SECURITY_DNS_TYPE"]
    SUGGESTION__DNS_SECURITY_DNS_FLAG = config["DNS Security"]["SUGGESTION__DNS_SECURITY_DNS_FLAG"]